apiVersion: 1
datasources:
  - name: GLPI-MySQL
    type: mysql
    url: mariadb:3306
    database: ${MYSQL_DATABASE}
    user: ${MYSQL_USER}
    secureJsonData:
      password: ${MYSQL_PASSWORD}
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
    isDefault: true